name: Project Build QA

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: "Bkamesh/Auth"
          ref: dev
          path: "Auth"

      - name: Restore Dependencies and Run Tests
        run: |
          dotnet restore "./Authentication/Authentication.csproj"
          dotnet test "./Authentication/Authentication.csproj"
        shell: cmd

      - name: Build Project
        run: dotnet build "./Authentication/Authentication.csproj" -c Release -o "D:/dotnet_build_files"
        shell: cmd

      - name: Publish Project
        run: dotnet publish "./Authentication/Authentication.csproj" -c Release -o "D:/dotnet_publish_files"
        shell: cmd
